export const chartStyles = {
  borderColor: { dark: '#4d4d50', light: '#e1e3eb' },
  backgroundColor: { dark: '#111112', light: '#ffffff' },
  titleColor: { dark: '#ffffff', light: '#0c152e' },
  textColor: { dark: '#70778b', light: '#70778b' },
  pointBackgroundColor: { dark: 'rgba(28, 28, 30, 0.8)', light: '#ffffff' },
  whiteColor: '#ffffff',
  platinumColor: '#e1e3eb',
  slateGray: '#70778b',
  blueGray: '#8a8ca2',
  manateeGray: '#9999a0',
  maastrichtBlue: '#0c152e',
  azule: '#0D75FD',
  azuleDark: '#0C31E2',
  ufoGreen: '#2bd67b',
  deepGreen: '#00d563',
  linthPink: '#f8d2d2',
  palePink: '#ffd0d1',
  pasterPink: '#fbd0d1',
  lightPurple: '#9747ff',
  deepPurple: '#8638e5',
  mystic: '#edf0f5',
  ghost: '#bec1cd',
  warningBorder: '#f7e36d',
  cobaltBlue: '#254798',
  burntSienna: '#ec6868',
  orange: '#ff7721',
  rainbowEnd: '#35f2b6',
  cloudBurst: '#1b243f',
  lightBlue: '#bde3ff',
  paleYellow: '#ffcd29',
  transparent: 'rgba(0, 0, 0, 0)',
  contentFontFamily: "'inter', sans-serif",
  fontSize: 13,
};

export const colorPalette = [
  chartStyles.ufoGreen,
  chartStyles.azule,
  chartStyles.slateGray,
  chartStyles.deepGreen,
  chartStyles.maastrichtBlue,
  chartStyles.linthPink,
  chartStyles.lightPurple,
  chartStyles.palePink,
  chartStyles.deepPurple,
  chartStyles.azuleDark,
  chartStyles.blueGray,
  chartStyles.burntSienna,
  chartStyles.manateeGray,
  chartStyles.orange,
  chartStyles.rainbowEnd,
  chartStyles.cloudBurst,
  chartStyles.lightBlue,
  chartStyles.paleYellow,
  chartStyles.ghost,
];

export const colorPaletteDark = [
  chartStyles.ufoGreen,
  chartStyles.azule,
  chartStyles.slateGray,
  chartStyles.deepGreen,
  chartStyles.warningBorder,
  chartStyles.pasterPink,
  chartStyles.lightPurple,
  chartStyles.palePink,
  chartStyles.deepPurple,
  chartStyles.cobaltBlue,
  chartStyles.blueGray,
  chartStyles.burntSienna,
  chartStyles.manateeGray,
  chartStyles.orange,
  chartStyles.rainbowEnd,
  chartStyles.cloudBurst,
  chartStyles.lightBlue,
  chartStyles.paleYellow,
  chartStyles.ghost,
];
