name: 'electron-build'

on:
  push:
    tags:
      - v3.*
    branches: [feature/*]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    environment: MACOS

    strategy:
      matrix:
#        os: [desktop-build, macos-latest]
        os: [desktop-build]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Setup node js runtime
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - uses: actions/setup-python@v4 #Install awscli on all platform
        with:
          python-version: '3.10'

      - name: Update package.json
        if: startsWith(matrix.os, 'macos')
        run: |
          jq '.build.mac.notarize.teamId = "${{ secrets.APPLE_TEAM_ID }}"' package.json > package_temp.json
          mv package_temp.json package.json

      - name: Install cpx
        if: startsWith(matrix.os, 'desktop-build')
        run: npm install -g cpx

      - name: Build and pack windows app
        if: startsWith(matrix.os, 'desktop-build')
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: pack:win
          github_token: ${{ secrets.github_token }}

      - name: Build and pack mac app
        if: startsWith(matrix.os, 'macos')
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: pack
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          github_token: ${{ secrets.github_token }}
        env:
          # macOS for notarization API key
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

      - name: Output Notarization Error Log
        if: failure() && startsWith(matrix.os, 'macos')
        run: |
          echo "Notarization failed. Outputting notarization-error.log..."
          cat /Users/runner/work/klayr-desktop/klayr-desktop/notarization-error.log
